### ISSUE TITLE
Should we support basic types for ChannelKinds?

### ISSUE THREAD

**Issue by dhylands** [fxbox/RFC#11]
For example, I need a String getter/setter to get/set the camera_name, username, and password, and it seems kind of lame that I need to create Extensions to do this.

Perhaps we can have a simple extension kind that is just a JSON object?
Why do we need a vendor for custom kinds and not for OnOff?

**Comment by Yoric** [comment]
If you don't mind, could you move that discussion to https://github.com/fxbox/taxonomy/issues/72? Unless I'm missing something, that doesn't really seem sound like RFC fodder to me.

As mentioned over there, `ChannelKind` is not about types but about feature discovery. As neither `String` nor `JSON` is  a feature, neither fits in `ChannelKind`. I don't see why you would create an `Extension` rather than a new variant, though. Since `Name`, `Username` and `Password` are pretty generic features, they would definitely fit in `ChannelKind` (at least until we adopt a plan for https://github.com/fxbox/RFC/issues/8 and get rid of `ChannelKind` entirely).

Regarding `vendor`: it's the name of whoever came up with the extension. Basically, it's a namespace, to avoid mismatches between two extensions with the same name.
